server:
  port: 8081
spring:
  application:
    name: Item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5s发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10s不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:  # 自动打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl